package server;

public class Content {
    public static String asciiArt = ""
    + "                  +##=                    \n"
    + "                =##*=##*                  \n"
    + "               =#%    *##                 \n"
    + "               ##      ##+                \n"
    + "              ##+       ##                \n"
    + "              #%        +#+               \n"
    + "             ##=         ##               \n"
    + "           =*###############=             \n"
    + "    =######%*##          -=+%%#####=      \n"
    + " =###*      -#%                   =###+   \n"
    + "###         =#%                      =##  \n"
    + "##+         +#%                       ##  \n"
    + " ###=       =#%                    =%##*  \n"
    + "   *####%=  =#%               =######     \n"
    + "        +%#####          #####%*          \n"
    + "             %##         ##               \n"
    + "             =#*        =#%               \n"
    + "              ##        %##               \n"
    + "              +##      =##                \n"
    + "               ##=    =##                 \n"
    + "                ###  +##                  \n"
    + "                  ####+                   \n";

    public static String cssString = ""
    + "<style>"
    + "body {"
    + "  font-family: Arial, sans-serif;"
    + "  background-color: #f8f9fa;"
    + "  margin: 0;"
    + "  padding: 0;"
    + "}"
    + "header {"
    + "  background-color: #343a40;"
    + "  color: #ffffff;"
    + "  padding: 20px;"
    + "  text-align: center;"
    + "}"
    + ".content-container {"
    + "  text-align: center;"
    + "}"
    + ".ascii-container {"
    + "  display: flex;"
    + "  justify-content: center;"
    + "  padding-top: 20px;"
    + "}"
    + "pre {"
    + "  font-size: 12px;"
    + "  white-space: pre-wrap;"
    + "  color: #343a40;"
    + "}"
    + "</style>"
    + "";
    
    public static String indexContentPrefix = ""
    + "<!DOCTYPE html>"
    + "<html lang=\"en\">"
    + "<head>"
    + "<meta charset=\"UTF-8\">"
    + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
    + cssString
    + "<title>Server</title>"
    + "</head>"
    + "<body>"
    + "<img src=\"static/images/emptystatedark.png\">"
    + "<header>"
    + "<h1>Welcome to the Server</h1>"
    + "</header>"
    + "<div class=\"ascii-container\">"
    + "<pre>"
    + asciiArt
    + "</pre>"
    + "</div>"
    + "<div style=\"padding-left: 100px; padding-right: 100px;\">";

    public static String indexContentSuffix = ""
    + "</div>"
    + "</body>"
    + "</html>";
}

